#!/usr/bin/env bash
# Starts the Next.js dev server wired to the simulation stack (scripts/dev-sim/index.ts must
# be running). Only Next.js starts; the Teams bot and diarisation tunnel are not needed.
#   scripts/dev-sim/start-app.sh
# Mode switch (optional): SIM_ACCESS_SOURCE=local starts the same app in local mode.
# SIM_REAL_LLM=1 drops the fake LLM so the app uses the real one configured in .env
# (OPENAI_API_KEY, optional LLM_BASE_URL / LLM_MODEL): minutes, chapters etc. are then
# generated by the real model and the transcript text leaves your machine. The acceptance
# scripts assume the fake LLM and will not pass in this mode.
set -euo pipefail
cd "$(dirname "$0")/../.."

ENV_FILE="$(mktemp)"
trap 'rm -f "$ENV_FILE"' EXIT
npx tsx scripts/dev-sim/index.ts --env > "$ENV_FILE"
set -a; . "$ENV_FILE"; set +a
if [ -n "${SIM_ACCESS_SOURCE:-}" ]; then export ACCESS_SOURCE="$SIM_ACCESS_SOURCE"; fi
# Variables set here win over .env (Next never overrides the environment, even with an empty value), so the
# fake LLM has to be unset, not just ignored, for the .env values to apply.
if [ "${SIM_REAL_LLM:-}" = "1" ]; then unset LLM_BASE_URL LLM_MODEL OPENAI_API_KEY; echo "[dev-sim] real LLM: using OPENAI_API_KEY / LLM_* from .env" >&2; fi
exec ./node_modules/.bin/next dev -p "${PORT:-3004}"
