export const MIN_TRANSCRIPT_LENGTH = 10;
export const MAX_TRANSCRIPT_LENGTH = 50000;

export const MIN_PROMPT_LENGTH = 10;
export const MAX_PROMPT_LENGTH = 4000;

export const MIN_HISTORY_TITLE_LENGTH = 5;
export const MAX_HISTORY_TITLE_LENGTH = 100;
