import { describe, it, expect } from 'vitest';
import { parseVtt, turnsFromVtt, segmentsFromVtt, speakersFromVtt } from './vtt';

// A realistic Teams export: BOM, CRLF, a NOTE block, GUID cue ids, entities,
// Danish names and æøå, a multi-line cue and a cue without a voice span.
const TEAMS_VTT = [
  '﻿WEBVTT',
  '',
  'NOTE Transcript generated by Microsoft Teams',
  '',
  '4f0d1a2b-9c11-4f7e-8a10-1/1-0',
  '00:00:03.120 --> 00:00:07.480',
  '<v Mette Hansen>Godmorgen alle sammen &amp; velkommen til mødet.</v>',
  '',
  '4f0d1a2b-9c11-4f7e-8a10-1/2-0',
  '00:00:07.900 --> 00:00:12.000',
  '<v Søren Østergaard>Tak. Jeg har et spørgsmål til',
  'punkt tre på dagsordenen.</v>',
  '',
  '00:00:12.400 --> 00:00:14.000',
  'Uklar tale i baggrunden',
  '',
].join('\r\n');

describe('parseVtt', () => {
  it('parses a Teams transcript with BOM, CRLF, NOTE blocks and cue ids', () => {
    const cues = parseVtt(TEAMS_VTT);
    expect(cues).toHaveLength(3);
    expect(cues[0]).toEqual({
      speaker: 'Mette Hansen',
      start: 3.12,
      end: 7.48,
      text: 'Godmorgen alle sammen & velkommen til mødet.',
    });
  });

  it('joins a multi-line cue payload into one line and keeps æøå', () => {
    const cues = parseVtt(TEAMS_VTT);
    expect(cues[1].speaker).toBe('Søren Østergaard');
    expect(cues[1].text).toBe('Tak. Jeg har et spørgsmål til punkt tre på dagsordenen.');
  });

  it('gives cues without a voice span a null speaker', () => {
    const cues = parseVtt(TEAMS_VTT);
    expect(cues[2].speaker).toBeNull();
    expect(cues[2].text).toBe('Uklar tale i baggrunden');
  });

  it('accepts MM:SS.mmm timestamps as well as HH:MM:SS.mmm', () => {
    const cues = parseVtt('WEBVTT\n\n01:05.250 --> 01:07.000\n<v A>hej</v>\n');
    expect(cues[0].start).toBeCloseTo(65.25, 5);
    expect(cues[0].end).toBeCloseTo(67, 5);
  });

  it('parses hour timestamps past one hour', () => {
    const cues = parseVtt('WEBVTT\n\n01:02:03.004 --> 01:02:04.000\n<v A>hej</v>\n');
    expect(cues[0].start).toBeCloseTo(3723.004, 5);
  });

  it('ignores cue settings after the end timestamp', () => {
    const cues = parseVtt(
      'WEBVTT\n\n00:00:01.000 --> 00:00:02.000 align:start position:10%\n<v Ida Bang>ja</v>\n',
    );
    expect(cues).toEqual([{ speaker: 'Ida Bang', start: 1, end: 2, text: 'ja' }]);
  });

  it('decodes named and numeric entities in text and speaker names', () => {
    const cues = parseVtt(
      'WEBVTT\n\n00:00:00.000 --> 00:00:01.000\n<v Anne &amp; Bo>1 &lt; 2 &gt; 0 &#39;ja&#39; &quot;nej&quot; &#xe6;</v>\n',
    );
    expect(cues[0].speaker).toBe('Anne & Bo');
    expect(cues[0].text).toBe('1 < 2 > 0 \'ja\' "nej" æ');
  });

  it('strips inline styling tags but keeps their text', () => {
    const cues = parseVtt(
      'WEBVTT\n\n00:00:00.000 --> 00:00:01.000\n<v.loud Ole Kjær><b>meget</b> vigtigt</v>\n',
    );
    expect(cues[0].speaker).toBe('Ole Kjær');
    expect(cues[0].text).toBe('meget vigtigt');
  });

  it('skips STYLE blocks and blocks without a timing line', () => {
    const cues = parseVtt(
      'WEBVTT\n\nSTYLE\n::cue { color: red }\n\nbare en overskrift\n\n00:00:00.000 --> 00:00:01.000\n<v A>hej</v>\n',
    );
    expect(cues).toHaveLength(1);
  });

  it('skips cues with unparseable timestamps instead of throwing', () => {
    const cues = parseVtt('WEBVTT\n\nabc --> def\n<v A>hej</v>\n\n00:00:01.000 --> 00:00:02.000\n<v B>ok</v>\n');
    expect(cues.map((c) => c.speaker)).toEqual(['B']);
  });

  it('returns an empty array for empty input', () => {
    expect(parseVtt('')).toEqual([]);
    expect(parseVtt('WEBVTT\n')).toEqual([]);
  });
});

describe('turnsFromVtt', () => {
  it('drops cues without a speaker', () => {
    const turns = turnsFromVtt(parseVtt(TEAMS_VTT));
    expect(turns.map((t) => t.speaker)).toEqual(['Mette Hansen', 'Søren Østergaard']);
  });

  it('merges adjacent cues from the same speaker across a short gap', () => {
    const cues = parseVtt(
      [
        'WEBVTT',
        '',
        '00:00:00.000 --> 00:00:02.000',
        '<v Mette Hansen>første sætning</v>',
        '',
        '00:00:02.200 --> 00:00:05.000',
        '<v Mette Hansen>anden sætning</v>',
        '',
      ].join('\n'),
    );
    expect(turnsFromVtt(cues)).toEqual([{ speaker: 'Mette Hansen', start: 0, end: 5 }]);
  });

  it('does not merge across a gap of 0.5s or more', () => {
    const cues = parseVtt(
      [
        'WEBVTT',
        '',
        '00:00:00.000 --> 00:00:02.000',
        '<v Mette Hansen>a</v>',
        '',
        '00:00:02.500 --> 00:00:05.000',
        '<v Mette Hansen>b</v>',
        '',
      ].join('\n'),
    );
    expect(turnsFromVtt(cues)).toEqual([
      { speaker: 'Mette Hansen', start: 0, end: 2 },
      { speaker: 'Mette Hansen', start: 2.5, end: 5 },
    ]);
  });

  it('keeps alternating speakers apart and merges overlapping same-speaker cues', () => {
    const cues = parseVtt(
      [
        'WEBVTT',
        '',
        '00:00:00.000 --> 00:00:03.000',
        '<v Mette Hansen>a</v>',
        '',
        '00:00:02.500 --> 00:00:06.000',
        '<v Søren Østergaard>b</v>', // overlapping interjection
        '',
        '00:00:05.800 --> 00:00:09.000',
        '<v Søren Østergaard>c</v>',
        '',
        '00:00:10.000 --> 00:00:12.000',
        '<v Mette Hansen>d</v>',
        '',
      ].join('\n'),
    );
    expect(turnsFromVtt(cues)).toEqual([
      { speaker: 'Mette Hansen', start: 0, end: 3 },
      { speaker: 'Søren Østergaard', start: 2.5, end: 9 },
      { speaker: 'Mette Hansen', start: 10, end: 12 },
    ]);
  });

  it('returns an empty timeline when no cue has a speaker', () => {
    expect(turnsFromVtt(parseVtt('WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nhej\n'))).toEqual([]);
  });
});

describe('segmentsFromVtt', () => {
  // A cue with no <v> span used to reach the review screen as "Taler 1" — an
  // unrecognised voice in a meeting whose speakers Teams had already named. It
  // now takes the name of whoever was speaking around it.
  it('maps cues one-to-one and names an unattributed cue after its neighbour', () => {
    expect(segmentsFromVtt(parseVtt(TEAMS_VTT))).toEqual([
      {
        speaker: 'Mette Hansen',
        start: 3.12,
        end: 7.48,
        text: 'Godmorgen alle sammen & velkommen til mødet.',
      },
      {
        speaker: 'Søren Østergaard',
        start: 7.9,
        end: 12,
        text: 'Tak. Jeg har et spørgsmål til punkt tre på dagsordenen.',
      },
      { speaker: 'Søren Østergaard', start: 12.4, end: 14, text: 'Uklar tale i baggrunden' },
    ]);
  });

  it('drops cues with no text', () => {
    const cues = parseVtt('WEBVTT\n\n00:00:00.000 --> 00:00:01.000\n<v A></v>\n');
    expect(segmentsFromVtt(cues)).toEqual([]);
  });
});

describe('speakersFromVtt', () => {
  it('lists distinct display names in first-appearance order', () => {
    const cues = parseVtt(
      [
        'WEBVTT',
        '',
        '00:00:00.000 --> 00:00:01.000',
        '<v Søren Østergaard>a</v>',
        '',
        '00:00:01.000 --> 00:00:02.000',
        '<v Mette Hansen>b</v>',
        '',
        '00:00:02.000 --> 00:00:03.000',
        '<v Søren Østergaard>c</v>',
        '',
        '00:00:03.000 --> 00:00:04.000',
        'ingen taler',
        '',
      ].join('\n'),
    );
    expect(speakersFromVtt(cues)).toEqual(['Søren Østergaard', 'Mette Hansen']);
  });
});
